/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Student {
  'id' : bigint,
  'name' : string,
  'feePaid' : number,
  'parentPhone' : string,
  'totalDays' : bigint,
  'attendanceLog' : Array<string>,
  'attendedDays' : bigint,
  'notes' : string,
  'enrollmentDate' : string,
  'course' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourses' : ActorMethod<[], Array<string>>,
  'getStudentById' : ActorMethod<[bigint], Student>,
  'getStudentByNameAndPhone' : ActorMethod<[string, string], [] | [Student]>,
  'getStudentsByCourse' : ActorMethod<[string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudents' : ActorMethod<[string], Array<Student>>,
  'updateStudentNotes' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];