/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'feePaid' : IDL.Float64,
  'parentPhone' : IDL.Text,
  'totalDays' : IDL.Nat,
  'attendanceLog' : IDL.Vec(IDL.Text),
  'attendedDays' : IDL.Nat,
  'notes' : IDL.Text,
  'enrollmentDate' : IDL.Text,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStudentById' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getStudentByNameAndPhone' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Student)],
      ['query'],
    ),
  'getStudentsByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'updateStudentNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'feePaid' : IDL.Float64,
    'parentPhone' : IDL.Text,
    'totalDays' : IDL.Nat,
    'attendanceLog' : IDL.Vec(IDL.Text),
    'attendedDays' : IDL.Nat,
    'notes' : IDL.Text,
    'enrollmentDate' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStudentById' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getStudentByNameAndPhone' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Student)],
        ['query'],
      ),
    'getStudentsByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'updateStudentNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };